# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    container_name: postgresql
    image: postgres:16.3
    restart: always
    shm_size: 128mb
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example